TRAINING_FILE = "../inputs/train.csv"
TRAINING_CLEAN = "../inputs/train_clean.csv"
TRAINING_SCALE = "../inputs/train_scale.csv"
TRAINING_NO_SCALE = "../inputs/train_no_scale.csv"
MODEL_PATH = "../models/model.pkl"
